version: "2"
services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/opt/app
      - /opt/app/node_modules
    ports:
      - "1102:1102"
    links:
      - mongo
    restart: on-failure:10
  mongo:
    container_name: olivia_mongo_1
    image: mongo:4.2.21
    ports:
      - "27017:27017"
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/opt/app
      - /opt/app/node_modules
    ports:
      - "8080:8080"
